baseurl: https://viollatlise.github.io/EEL
languageCode: en-us
theme: hugo-theme-hello-friend
paginate: 5
params:
  contentTypeName: post
  defaultTheme: dark
  showMenuItems: 3
  showReadingTime: no
languages:
  en:
    copyright: ''
    dateFormatList: '2006-01-02'
    dateFormatSingle: '2006-01-02'
    keywords: ''
    menu:
      main:
        - identifier: about
          name: About
          url: /about
        - identifier: anguilliform
          name: Anguilliforms
          url: /anguilliform
        - identifier: species
          name: Species
          url: /species
    menuMore: Show more
    minuteReadingTime: min read
    newerPosts: Newer posts
    olderPosts: Older posts
    params:
      logo:
        logoHomeLink: https://viollatlise.github.io/EEL/
        logoText: EELS
    readMore: Read more
    readOtherPosts: Read other posts
    subtitle: A simple blog about eel
    title: Hello eels lovers! 
